---
- name: Apply the Hush Gitian builder role.
  become: yes
  hosts: localhost:hush-build
  vars:
    hush_git_repo_url: https://github.com/MyHush/hush
    hush_version: v1.0.12
    gpg_key_name: ''
    git_name: ''
    git_email: ''
    gpg_key_id: '' # optional
    ssh_key_name: '' # optional
  roles:
    - role: common
      tags: common
    - role: gitian
      tags: gitian
